name: Optimize Images
on: [pull_request]
jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: calibreapp/image-actions@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
          formats: "[\"jpg\",\"jpeg\",\"png\",\"webp\"]"
