name: Link Checker
on: [pull_request, workflow_dispatch]
jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --verbose --exclude-mail ./**/*.html
