name: Super Linter

permissions:
  contents: read
  statuses: write
  checks: write

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CSS: false
          VALIDATE_HTML: false
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          MARKDOWN_CONFIG_FILE: .markdownlint.json
          FILTER_REGEX_EXCLUDE: .*Images/.*|.*daniels-resume\.pdf
